### ISSUE TITLE
Token recognition error relating to the ColourID 

### ISSUE THREAD

**Issue by tyrantina** [YarnSpinnerTool/YarnSpinner-Unity#10]
**What is the current behavior?**
Receiving an error about the token recognition in the colourID line. May possibly be because I'm still updating the syntax of the project

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
The issue is created by loading the yarn file into unity.

**What is the expected behavior?**
The file should be loading into unity as a recognized yarn file. 

**Please tell us about your environment:**

  - Yarn Spinner Version: 1.10
  - Unity Version: 2019.2.0f1

**Other information** 

[You're Not Yorak.zip](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/files/4786036/You.re.Not.Yorak.zip)

**Comment by WeslomPo** [comment]
This is error in parser/lexer/etc, not in unity addon.
Actually you have line with this symbols at 1101, "]]]"
`[[I'll do better sir|RemoveHumanSuit]]]`
You need to write it like:
`[[I'll do better sir|RemoveHumanSuit]]`
And it will fix that.

**Comment by tyrantina** [comment]
Thank you so much. 
Didn't proofread my code properly.
