### ISSUE TITLE
SetValue() reports Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Yulovery** [YarnSpinnerTool/YarnSpinner-Unity#108]
`InMemoryVariableStorage.SetValue("$varToSet", valueToSetTo)`
report error Object reference not set to an instance of an object. despite defining the $varToSet in YarnProgram, or Defualt Variables, or adding it in the the Variable dictionary manually.

myCodes:

`public InMemoryVariableStorage varStor;`
`varStor = dialogueRunner.GetComponent<InMemoryVariableStorage>();`
`trys = 1;
var valueToSet = new Yarn.Value(trys);
 varStor.SetValue("$wakeTimes", valueToSet);`

  - Yarn Spinner Version: 1.2.6?
  - Unity Version: 2014.4.28f1c1

**Comment by desplesda** [comment]
Looking at the code for InMemoryVariableStorage, I don't see a way for a null reference exception to occur (because all of the fields that it uses are guaranteed to be defined when the method is called). 

Is it possible that this issue is being caused by your call to `dialogueRunner.GetComponent`?

**Comment by desplesda** [comment]
I haven't heard anything further on this, so I'll close this issue here. Please re-open if you're continuing to see this!
