### ISSUE TITLE
Built in functions for common patterns in games

### ISSUE THREAD

**Issue by McJones** [YarnSpinnerTool/YarnSpinner-Unity#113]
**Is your feature request related to a problem? Please describe.**

There are a few common functions that many games need and are often rewritten time and time again.
Such common functions should be built into the unity function library directly instead of requiring people to make them themselves.
In particular the two most common functions seen in use are a function to tell if a node has been visited before and random number generation.
I propose we add both of these into the library directly.

**Describe the solution you'd like**

I propose we add in three new functions directly to the library that all Yarn projects will have access to, `visited`, `random`, `dice`.
Names at this stage are open to bikeshedding and chosen mostly arbitrarily.
`visited` will take in a single `String` parameter and will return a `boolean` if the node with that name has been exited before in the current run of the project. Should the parameter not match a Yarn node or be invalid for a Yarn node name the result will be false.
`random` will return a `number` between 0 and 1 inclusively.
`dice` will take in a single `number` as parameter and will return a `number` randomly between the range of 1 -> parameter inclusively. This number will always be an integer return. The parameter must be greater than 1, if it isn't the return result will always be 1.

The intention of `random` vs `dice` is for as their name suggests when you need a random number vs a dice/coin toss.
So if you need a standard D6 dice `dice(6)` is much nicer than having to multiply and round `random`.

Example of said functions in use:
```
<<if visited("thisNodesName")>>
Ah, I see you've returned.
<<endif>>

<<if random() > 0.5>>
Seems to me like this happens half the time, eh?
<<endif>>

<<set $d1 = dice(6)>>
<<set $d2 = dice(6)>>
<<if $d1 == 1 && $d2 == 1>>
Snake eyes!
<<elseif $d1 + $d2 == 7>>
as expected
<<endif>>
```

**Describe alternatives you've considered**

Keep the number of built in functions as is (so just the type casting functions), there is nothing wrong with this its just not very much in the spirit of the project...

Random and Dice functions could be combined, but I feel they are distinct enough and having to essentially clean up the result of random to force it into an integer form feels worth while having its own function.

There is also a great deal of space here for additional common functions but these three feel like the best starting point.

**Additional context**

the Random and Dice functions can be static functions on the Dialogue Runner itself, visited however will need to have some sort of interaction with the dialogue to work.

**Comment by desplesda** [comment]
I'm in favour of adding this. The two random number generation methods you suggest, `dice` and `random`, are simple enough to do immediately; the `visited` method is a little more complex, because it would need to store and fetch information about nodes that have been visited.

We've had a couple of conversations about how a `visited` system might work, including adding special compiler support for a visit-tracking system; I'd like to suggest that `visited` be removed from this proposal and moved into one on its own.

**Comment by McJones** [comment]
sure makes sense to split visited off onto its own thing instead of having it hold back other useful functions.
I guess the only question then is are there any other functions we'd want to add in at the same time?
