### ISSUE TITLE
lineView.OnContinueClicked() does not behave correctly when Line View is not first in the DialogueRunner.dialogueViews

### ISSUE THREAD

**Issue by fmoo** [YarnSpinnerTool/YarnSpinner-Unity#115]
**What is the current behavior?**

When Line View is placed after Dialogue Character Name View in the DialogueRunner's dialogueViews list, triggering "OnContinueClicked" causes the text to immediately switch to the next line of text, and the typewriter to reset after a few frames of rendering the new dialogue, instead of interrupting the typewriter and displaying the remainder of the line.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

1. Set up your DialogueRunner with a Line view and a Dialogue Character Name View
2. Enable typewriter text on the Line View (with a speed of like 15-25)
3. Make sure the Line View is *last*
4. Trigger a long dialogue with at least two messages
5. While the typewriter text is still running on the first message, trigger an action that calls OnContinueClicked().

**What is the expected behavior?**

The expected behavior is that the typewriter text is interrupted, and the remainder of the message is displayed.

What actually happens is that the message typewriter is interrupted, resets to the next message immediately, resets the typewriter, and then after displaying a few characters of the next message, the typewriter resets a second time, displaying the text a bit faster than normal.   If you continue to skip through the rest of the messages, you'll eventually get some LogError calls from stale typewriter text coroutines completing while no dialogue is running.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0.0-beta5
  - Unity Version: 2021.1.1f1

**Other information**

**Comment by McJones** [comment]
I believe this was fixed as part of commit 8ce56ae.
If the issue persists please open a new issue.
