### ISSUE TITLE
Package from git URL BUG - Unity 2020.3.9f Packager Manager 

### ISSUE THREAD

**Issue by romuloyoosfranco** [YarnSpinnerTool/YarnSpinner-Unity#131]
Hi! I tried to download YarnSpinner via the Package Manager in unity but there's an error every time I try to copy and past the GitHub link in the PackageManager.

What I did, step by step:

Opened unity > Package Manager > " + " > ADD package from git URL > Paste the link ( https://github.com/YarnSpinnerTool/YarnSpinner-Unity.git) > Error

I followed this Youtube tutorial: https://youtu.be/4n3AvsB6JRo?t=84

**Comment by McJones** [comment]
Can you give us any more information about the error?
Did it have any additional information we can use to work out what's happened?

Also what version of Unity are you using?

**Comment by romuloyoosfranco** [comment]
![image](https://user-images.githubusercontent.com/44445309/140421361-6fce6331-77fe-4a26-8b21-3e75baf36981.png)

**Comment by romuloyoosfranco** [comment]
I tried to download the  Package via "add package from link URL" and there's this text telling the error. I don't know WHY! =(

**Comment by McJones** [comment]
that error is most often found when you have a mistake in the URL, it looks right but there might be a rogue space, https://docs.unity3d.com/Manual/upm-errors.html#bad-url does following that help?

**Comment by McJones** [comment]
There's been no movement on this for a while now, closing them.
Feel free to reopen if the issue persists.
