### ISSUE TITLE
FMod 2.02 deprecates EventRef for EventReference

### ISSUE THREAD

**Issue by unknowndevice** [YarnSpinnerTool/YarnSpinner-Unity#150]
**What is the current behavior?**

If you upgrade to the latest version fmod you will get a deprecated warning for EventRef

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Install fmod package 2.02 and you will see the warnings

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0.2 
  - Unity Version: any 
  - Fmod 2.0.2

**Other information** 

* https://www.fmod.com/resources/documentation-api?version=2.02&page=welcome-whats-new-202.html
* https://www.fmod.com/resources/documentation-unity?version=2.02&page=examples-basic.html

**Comment by desplesda** [comment]
We've since removed the FMOD integration as of v2.1.0, which means this source code no longer appears, and therefore, this issue doesn't apply. Thanks for filing the issue!
