### ISSUE TITLE
Application crash during DialogueRunner Start function (Windows)

### ISSUE THREAD

**Issue by Nicolas-Ilareguy** [YarnSpinnerTool/YarnSpinner-Unity#151]
**What is the current behavior?**
Application crashes on launch.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
1- Build the application on Windows.
2- Launch the application.
3- The application crash; the logs point to the Dialogue Runner Start() function when it tries to create delegates.

**What is the expected behavior?**
The application does not crash when launched.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0.2-development
  - Unity Version: 2021.2.7f1

**Other information** 

Crash Log / Stacktrace:

0x00007FFB52043E3F il2cpp::vm::Type::ConstructDelegate 
0x00007FFB520B204D il2cpp::icalls::mscorlib::System::Delegate::CreateDelegate_internal 
0x00007FFB4EF9B490 Delegate_CreateDelegate_mE57A1F8CC813EF670D026C17D2D4CFD7C6E3F40A 
0x00007FFB4EF9AC05 Delegate_CreateDelegate_mA2E221A01A8B3FBEC4C8A529F3C213C60A3A2C53 
0x00007FFB4ED9C5B9 RuntimeMethodInfo_CreateDelegate_m026E9DD922CC53D92EA3A3529A1BC089ABD0B8B9 
0x00007FFB51FAD952 ActionManager_GetFunctionRunner_m7BB545776DC22611A918361CC0FCBD07B9EEB7E9 
0x00007FFB51FAAD2B ActionManager_FindAllActions_m7DE3020C8F3476B34990442939FD237BC049289A 
0x00007FFB51FA6223 ActionManager_AddActionsFromAssemblies_mCC3AC961DB087BA139C9D46E33448CBC7E5514F7 
0x00007FFB51FCA62D DialogueRunner_Start_mDB146186494B91F0EEA6C010E6687C8DED346C12 

Exception Code: 0xC0000005
Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

More information: We also removed the DialogueRunner script from our scene and the build was not crashing anymore, so it's definitely the culprit. The issue is not present in the Unity Editor.

**Comment by Nicolas-Ilareguy** [comment]
Just to be sure that the issue wasn't from my project. I downloaded the Choose-Your-Path Game project from the documentation, setup the script so the project was completable and built it for Windows as well. Same issue, it crashes on launch with the same stacktrace.

**Comment by jramstedt** [comment]
IL2CPP build on Android crashes too when dialogue is started.

**Comment by McJones** [comment]
I think this and #163 may be related, they are both looking like IL2CPP build woes.
I am leaving this up for now as I do some more testing, but may close this and open a meta-issue or merge these issues instead if it turns out to be connected.

**Comment by McJones** [comment]
I have been doing some testing and while I am not an M1 Mac I couldn't get a crash here on il2cpp builds, will have to investigate further, but it looks like it might be trickier than *just* an il2cpp issue.

**Comment by McJones** [comment]
This is connected to #163 and while that issue was filed second that one has more details so I will close this one and leave that as the discussion point
