### ISSUE TITLE
Allow variables inside <<jump "node">> command

### ISSUE THREAD

**Issue by ElliotEserinST** [YarnSpinnerTool/YarnSpinner-Unity#157]
I want to be able to jump to a node that has been saved in a variable. 

Id love to be able to call <<jump $some_node>> but it currently throws "Error: token recognition error at: '$'" and I assume its because its not possible.

I realise I could do this with a lot of <<if >> lines but that's more prone to human error and isn't great for extensive lists of nodes...

If its not possible, that's fine. Just think itd be neat. :) thanks for all of your hard work developing this. Its really awesome!

**Comment by desplesda** [comment]
Good news! This has [already been implemented](https://github.com/YarnSpinnerTool/YarnSpinner/issues/301), and will ship in the next release of Yarn Spinner.
