### ISSUE TITLE
Setting the value of a variable with a function causes a Yarn compile error

### ISSUE THREAD

**Issue by KXI-System** [YarnSpinnerTool/YarnSpinner-Unity#158]
**What is the current behavior?**
When setting a variable in yarn with a function like so:
```
<<set $cats = getCats()>>
```

Causes this compile error to happen:
```
Error compiling: 5:0: Error: $cats (Number) cannot be assigned a undefined
```

However, this workaround does not create a compile error.
```
<<set $cats = getCats() + 0>>
```

The function could be registered through code or with the attribute, and works just fine in other contexts.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Given the following Yarn file:
```
title: Start
tags: 
position: 100,100
---
<<set $cats = getCats()>>
===
```

With the function:
```csharp
dialogueRunner.AddFunction("getCats", () =>
{
	return 2;
});
```

Throws the error:
```
Error compiling: 5:0: Error: $cats (Number) cannot be assigned a undefined
```

This is true for string and bool story variables and functions, you can apply a similar workaround for string functions but not bool functions.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0.2

**Other information** 
It seems that the compiler can't tell the return type for a function, while it is technically possible to use a function that returns a different type to the variable you are setting the compiler does not make that distinction.

**Comment by KXI-System** [comment]
**Current Workarounds**

As this was Discussed on the discord, here are workarounds to use in the meantime.

Using casting functions to tell the compiler which type to use:
```
<<set $myNumber = number( getNumber() )>>
<<set $myString = string( getString() )>>
<<set $myBool = bool( getBool() )>>
```

There is also the appending an empty value mentioned in the first post, but it would only work with strings and numbers.
```
<<set $myNumber = getNumber() + 0>>
<<set $myString = getString() + "">>
```

**Comment by McJones** [comment]
For some reason this issue didn't auto close when #162 was merged. Closing it, thanks for filing it.
