### ISSUE TITLE
LineView: Turning off 'Use Fade Effect' makes Continue button stop working after first use

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner-Unity#161]
**What is the current behavior?**

When 'Use Fade Effect' is turned off in the LineView inspector, the Continue button is dimmed and disabled after clicking it for the first time.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

1. Create a new, empty project, with Yarn Spinner installed. 
2. Add the Dialogue System to the empty scene.
3. Create a new Yarn Script and Yarn Project. Add at least two lines to the Yarn Script.
4. Select the Line View, and turn off Use Fade Effect. 
5. Play the scene. Observe the first line, and that the Continue button is clickable.
6. Click the Continue button. Observe that the Continue button is now not clickable, and it is not possible to proceed beyond the second line of dialogue.

**What is the expected behavior?**

The continue button should remain clickable.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.1.0
  - Unity Version: 2020.3.20

**Other information** 

* This issue is also reproducible when Use Typewriter Effect is also turned off.
* Behaviour is normal when Use Fade Effect is left on.

**Comment by NeedsLoomis** [comment]
Can confirm.  Moving the continue button so it is no longer a child of the Line View is a work around.
