### ISSUE TITLE
YarnProject without declarations produces exception in editor

### ISSUE THREAD

**Issue by sttz** [YarnSpinnerTool/YarnSpinner-Unity#168]
**What is the current behavior?**

When selecting a YarnProject in the editor that doesn't contain any declarations, a number of exceptions are thrown and logged in the console.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
- Create a new empty Yarn Project and open it in the inspector
- Observe exceptions printed in the console

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.1.0
  - Unity Version: 2021.2.18

**Other information** 

This is due to `UnityEditorInternal.ReorderableList` calling its `elementHeightCallback` even if the list is empty and `ReorderableDeclarationsList.GetElementHeight` not checking if the given index is in bounds.

You can see `ReorderableList`'s source code [here](https://github.com/Unity-Technologies/UnityCsReference/blob/2020.3/Editor/Mono/GUI/ReorderableList.cs#L690) and follow `DoLayoutList` → `GetListElementHeight` → `CacheIfNeeded`, which then invokes `elementHeightCallback?.Invoke(0)` [here](https://github.com/Unity-Technologies/UnityCsReference/blob/2020.3/Editor/Mono/GUI/ReorderableList.cs#L552). At no point is the length of the list checked.

I added a check for the list length in `ReorderableDeclarationsList.GetElementHeight` and the exceptions went away:
```cs
if (serializedProperty.arraySize == 0)
{
    return 0;
}
```

**Comment by desplesda** [comment]
Thank you for the extremely clear and well-researched issue!

Would you be willing to open a pull request that merges your fix?

**Comment by McJones** [comment]
I can't reproduce this from the current version in main.
It's possible that this was fixed as part of the recent modifications of the backwards type inference.
Leaving this open for now in case it reappears a bit later.

**Comment by sttz** [comment]
Can reproduce it with 13d60e64 from main on Unity 2021.2.18.

Looks like Unity has fixed `ReorderableList` in 2022.1 and only call `elementHeightCallback` if the list contains elements:
https://github.com/Unity-Technologies/UnityCsReference/blob/2022.1/Editor/Mono/GUI/ReorderableList.cs#L548

So you'll need Unity 2021.2 or earlier to reproduce the issue.

Opened pull request #171 with the above fix.
