### ISSUE TITLE
Move Culture struct under a namespace

### ISSUE THREAD

**Issue by Haapavuo** [YarnSpinnerTool/YarnSpinner-Unity#17]
**Is your feature request related to a problem? Please describe.**
Culture struct is currently not inside any namespace and this may cause conflicts with existing scripts.

**Describe the solution you'd like**
Move Culture struct into a namespace (i.e. "Yarn").

**Comment by McJones** [comment]
This was fixed ages ago, for some reason the commit didn't autoclose the issue.
Closed
