### ISSUE TITLE
DialogueAdvanceInput not working with OptionsListView on certain inputs

### ISSUE THREAD

**Issue by flexayoung** [YarnSpinnerTool/YarnSpinner-Unity#172]
**What is the current behavior?**
When I add `DialogueAdvanceInput` to `OptionsListView` and set the input to the E key it does not advance the dialogue-view.  Although it does work with other inputs such as Space. The `DialogueAdvanceInput` also works fine with input-key E for the `LineView`.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Place the `DialogueAdvanceInput` on the `OptionsListView` GameObject and set the `DialogueView: LineView`, `ContinueActionType: KeyCode` and `ContinueActionKeyCode: E` it works as expected, however when I do the same on `OptionsListView` I cannot use E to advance, however when I change the input to Space it does advance.

**What is the expected behavior?**
When I press E on a dialogue option the dialogue view should advance to the next view.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.1.0
  - Unity Version: 2020.3.3

**Comment by ketexon** [comment]
`OptionsListView` does not handle input, it only spawns buttons as `OptionView`s. The reason space works is that by default, space is registered to "Submit" in the old input system. 
You can make `DialogueAdvanceInput` work with `OptionsListView` by creating a subclass for (or modifying) `OptionsListView` to override `UserRequestedViewAdvancement`, in which you find the focused button and call `OnSubmit`, but it probably would be better to change the `Submit` binding to include your desired button.
(There is still the problem that `DialogueAdvanceInput` cannot use buttons in the old input system).

**Comment by McJones** [comment]
This is correct. `OptionsListView` doesn't have a notion of "advance to the next piece of content", because it relies on the player choosing a specific item from the list of choices. There's no concept of "next", only "which".

If you want to have an options view select a 'default' choice, then creating a custom dialogue view (as ketexon suggests) is the way to go.
