### ISSUE TITLE
Unity.Localization Support

### ISSUE THREAD

**Issue by robertdhernandez** [YarnSpinnerTool/YarnSpinner-Unity#175]
**Is your feature request related to a problem? Please describe.**
Unity 2021 LTS officially has a new package called [Unity.Localization](https://docs.unity3d.com/Packages/com.unity.localization@1.2/manual/index.html) for handling localization through Addressables. This package is also available for Unity 2020 LTS, however it must be manually imported via the package manager. Notably, it is not defined as a preview package for 2020 LTS; it's just hidden.

**Describe the solution you'd like**
I would like official support with the Localization package, so that the localization can be defined in one area rather than split between Yarn's implementation and Unity's implementation. Yarn is already half-way there with the solution, largely just needing the ability to export to a pre-defined [string table](https://docs.unity3d.com/Packages/com.unity.localization@1.2/manual/StringTables.html?q=string%20table) from the Yarn Project at edit time. From there, the line provider would fetch the entry and feed it into the dialogue view.

**Comment by McJones** [comment]
This is fixed in #185 and will resolved when that is merged, as such closing this issue for now.
