### ISSUE TITLE
Tag is inserted at a wrong position when emoji exists

### ISSUE THREAD

**Issue by houkanshan** [YarnSpinnerTool/YarnSpinner-Unity#177]
**What is the current behavior?**

I believe this is an issue of YarnSpinner core, if you want me to move it let me know. Thanks!

I believe there's an inconsistency while calculating the length of multi-character character like emoji. 
While getting the length it think the length of an 2-char emoji is 1. 
While adding with new tags, it think the length is 2+. 

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

1. use this yarn file
```yarn
title: TestEmoji
tags:
---
A: test
B: test 😱
A: test
B: test 😱
A: test
B: test 😱
A: test
B: test 😱
A: test
B: test 😱
A: test
B: test 😱
===
```
2. Click Add Line Tags to Scripts in Unity
3. Generated yarn file

```yarn
title: TestEmoji
tags:
---
A: test #line:061e7a0 
B: test � #line:0107a54 �
A: tes #line:0c79810 t
B: test  #line:0565fe8 😱
A: te #line:07627f9 st
B: test #line:09f802a  😱
A: t #line:01a5986 est
B: tes #line:07943d1 t 😱
A:  #line:0fd52f6 test
B: te #line:0b052e7 st 😱
A: #line:0741153  test
B: t #line:07285f0 est 😱

===
```

**What is the expected behavior?**

line tags should be at the end of lines.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.1.0
  - Unity Version: 2021.1.28f

**Other information** 

I believe this issue doesn't exist in v2.0.0-beta5

**Comment by houkanshan** [comment]
For someone who has the same issue, here is a temporary workaround I'm using:

Add these two blocks around https://github.com/YarnSpinnerTool/YarnSpinner-Unity/blob/main/Editor/Utility/YarnProjectUtility.cs#L508

```diff
+                   var emojiQueue = new Queue<string>();
+                   var regex = new Regex(@"([\uD800-\uDBFF])([\uDC00-\uDFFF])");
+                   contents = regex.Replace(contents, match =>
+                   {
+                       emojiQueue.Enqueue(match.Value);
+                       return "~~emoji~~";
+                   });
                    
                    // Produce a version of this file that contains line
                    // tags added where they're needed.
                    var taggedVersion = Yarn.Compiler.Utility.AddTagsToLines(contents, allExistingTags);
                    
+                   regex = new Regex(@"~~emoji~~");
+                   taggedVersion = regex.Replace(taggedVersion, _ =>                    {
+                       return emojiQueue.Dequeue();
+                   });

```

**Comment by McJones** [comment]
This is related to https://github.com/YarnSpinnerTool/YarnSpinner/issues/323 and is due to how we incorrectly assume the length of all symbols to be a single byte.
A proper fix requires some changes in the core repo.
