### ISSUE TITLE
Add Metadata To Node

### ISSUE THREAD

**Issue by alijaya** [YarnSpinnerTool/YarnSpinner-Unity#181]
I think it's a good idea and low effort if we could add additional metadata field in Node besides `title` or `tag`.

This will be useful when we want to use storylet narrative design.

This is some resource about storylet:
https://emshort.blog/2019/11/29/storylets-you-want-them/
https://mkremins.github.io/publications/Storylets_SketchingAMap.pdf

**Comment by McJones** [comment]
Fixed in https://github.com/YarnSpinnerTool/YarnSpinner/commit/840c003f93779bc38cae81188ec174ab61d3c122
