### ISSUE TITLE
Cannot stop a dialogue

### ISSUE THREAD

**Issue by gwc0111** [YarnSpinnerTool/YarnSpinner-Unity#184]
I want to skip a dialogue. Then I call runner.stop(), but it is unuseable. Maybe there is a bug about it?

**Comment by gwc0111** [comment]
![image](https://user-images.githubusercontent.com/21290593/178300385-0d5f28a0-e618-4921-bc88-744638efac8b.png)
![image](https://user-images.githubusercontent.com/21290593/178300395-353f3be0-0e00-4d07-a47b-63ff8cfff708.png)

**Comment by gwc0111** [comment]
No, it is not that.
When i call Stop, the runner can't be stopped, instead of it, it will replay the text again.

**Comment by gwc0111** [comment]
I tried again by close UI manully, and it it successful! Thank you very much.




高伟成
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YarnSpinnerTool/YarnSpinner-Unity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 凌晨3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YarnSpinnerTool/YarnSpinner-Unity] Cannot stop a dialogue (Issue #184)





 
I don’t know what your exact problem is, but I’m just inferring from the conversation on Discord and your screenshots.
 
DialogueRunner.Stop only stops the Dialogue Runner from running, it does not dismiss any of the Dialogue Views (hiding the UI) and does not trigger any Dialogue Complete events. It does not pause the dialogue at all.
 
From the code you posted, it works as expected. Both your OnStop and OnStart have the same Debug.Log message. StartDialogue will always start the dialogue at the beginning of the node. As mentioned before, Stop will only stop the Dialogue Runner, and the UI from your Dialogue Views still remain since you haven’t done anything to dismiss or hide them.

**Comment by samanabo** [comment]
How did you solve this issue? I'm currently seeing the same problem, where after calling `Stop` the first line of dialog will play again, and leave the UI open.
Even if I manually call `DismissLine` or other similar functions it seems like eventually `ContinueDialogue` is called by the system and the UI pops up.
I suspect this issue is the same problem: https://github.com/YarnSpinnerTool/YarnSpinner-Unity/issues/186

**Comment by gwc0111** [comment]
> How did you solve this issue? I'm currently seeing the same problem, where after calling `Stop` the first line of dialog will play again, and leave the UI open.
> Even if I manually call `DismissLine` or other similar functions it seems like eventually `ContinueDialogue` is called by the system and the UI pops up.
> I suspect this issue is the same problem: #186

Yes, I have already solved this problem. You can first go to the help section of Discord and search for chat records related to the user "Alain#6244". I have asked about this issue there and successfully solved it. If that doesn't work, please ask again on GitHub, and I will look for the relevant code.
