### ISSUE TITLE
Unity 2020.1 version does not include [NonReorderable] Attribute

### ISSUE THREAD

**Issue by OU2018** [YarnSpinnerTool/YarnSpinner-Unity#195]
**What is the current behavior?**
Library\PackageCache\dev.yarnspinner.unity@ac33e9168b\Editor\Importers\YarnProjectImporter.cs(137,10): error CS0246: The type or namespace name 'NonReorderableAttribute' could not be found (are you missing a using directive or an assembly reference?)
Library\PackageCache\dev.yarnspinner.unity@ac33e9168b\Editor\Importers\YarnProjectImporter.cs(137,10): error CS0246: The type or namespace name 'NonReorderable' could not be found (are you missing a using directive or an assembly reference?)

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Using Unity 2020.1.14f1 version, import the YarnSpinner plugin from git.

**What is the expected behavior?**
no error.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2.1
  - Unity Version:Unity 2020.1.14f1 Personal

**Other information** 

I found a way to fix this problem. It is to change UNITY_2020_1 in the wrong place to UNITY_2020_2. Because there is no [NonReorderable] in the 2020.1 version of the manual, it will be available in 2020.2.

**Comment by desplesda** [comment]
Fixed. Thank you for the report!
