### ISSUE TITLE
Release build crash on every Dialogue.LoadString() call

### ISSUE THREAD

**Issue by isaacmarco** [YarnSpinnerTool/YarnSpinner-Unity#197]
**What is the current behavior?**
Development-builds works fine, but release-builds always crashs on Dialogue.LoadStrings() method calls

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
1. Assign a TextAsset to DialogueRunner.sourceText field
2. Call Dialogue.LoadString() method
3. Build a release build and run on Nintendo Switch 

*Please tell us about your environment:**
  
  - Yarn Spinner Version: DLL Version=1.0.6421.29891
  - Unity Version: Unity 2019.4.36f1 (With Nintendo Switch addon)

**Other information** 
YarnSpinner does not throw any exceptions during its execution in a development-build and everything works fine. Is the YarnSpinner DLL provided in the Unity package intended to be used in release-builds?

**Comment by desplesda** [comment]
We're looking into this, but please note that we can't discuss much about it in a public forum due to our NDA with Nintendo.

**Comment by desplesda** [comment]
Closing this issue due to its age; support for runtime loading of Yarn scripts is on our radar for a future release.
