### ISSUE TITLE
OnDialogueStarted and OnDialogueStopped UnityEvents on DialogueRunner

### ISSUE THREAD

**Issue by nrvllrgrs** [YarnSpinnerTool/YarnSpinner-Unity#201]
The player starts a dialogue when they enter a trigger. This action does not remove control from the player. When the player exits a trigger, the dialogue stops. However, the UI remains visible.

I would like the DialogueRunner to expose OnDialogueStart and OnDialogueStop events, similar to its OnNodeComplete event. This would allow me to register to when the IsDialogueRunning property changes.

**Comment by McJones** [comment]
Fixed as part of fd07a67
