### ISSUE TITLE
Modify TypewriterEffectSpeed by code or built-in command

### ISSUE THREAD

**Issue by matthers3** [YarnSpinnerTool/YarnSpinner-Unity#202]
**Is your feature request related to a problem? Please describe.**

I want to modify a LineView typewriter effect speed through code, but the variable is internal and there are no getters or setters.

**Describe the solution you'd like**

Having a built-in command to use from a Yarn Script or a method to modify such value through a custom command.

**Describe alternatives you've considered**

Adding a getter or setter in the LineView class for the typeWriterEffectSpeed variable, or a method that modifies such value.

**Additional context**

I had to make a copy of this class and add a property to modify it. It was quite fast to do, but I was wondering if this is a common issue. Thanks for your time!

**Comment by JonKleehammer** [comment]
Just wanted to leave a comment and show my interest in this feature as well.
Feels like a common use to me, some lines or even individual words could be faster or longer depending on the emotional state of the speaker.

**Comment by McJones** [comment]
After a bit of discussion around this issue we have decided to close this issue.
We don't see the typewriter effect, or the default effects and views as meant to work for everyone in every situation, they are to help you get started.

As the original post mentioned you can add this in yourself by duplicating the typewriter effect code to extend it however you want.
If you really need a lot of control over the effects and display of the code that is what [creating your own custom](https://docs.yarnspinner.dev/using-yarnspinner-with-unity/components/dialogue-view/custom-dialogue-views) views are for and we suggest that people interested in that level of control do so.
