### ISSUE TITLE
UnityLocalisedLineProvider assetTable should check for IsEmpty

### ISSUE THREAD

**Issue by samanabo** [YarnSpinnerTool/YarnSpinner-Unity#205]
**What is the current behavior?**
In the new UnityLocalisedLineProvider (currently experimental) there is a check if the stringsTable is null on lines 51 and the assetTable on line 55. However, it is possible for these values to be non-null, but still be empty causing an error.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
1. Open a project with the experimental compiler option enabled `YARN_ENABLE_EXPERIMENTAL_FEATURES`
2. Add the unityLocalisedLineProvider to the dialogRunner
3. Do not select a value in the editor for stringsTable or assetTable
4. Press play, notice the error in the console (see below)

**What is the expected behavior?**
These fields should check for `IsEmpty` for example `!stringTable.IsEmpty` and `!assetTable.IsEmpty`

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2.2
  - Unity Version: 2022.1.10f1

**Other information** 
```ArgumentException: Empty Table Reference. Must contain a Guid or Table Collection Name
UnityEngine.Localization.Tables.TableReference.Validate () (at Library/PackageCache/com.unity.localization@1.3.2/Runtime/Tables/TableReference.cs:167)
UnityEngine.Localization.Settings.LocalizedDatabase`2[TTable,TEntry].GetTableAsync (UnityEngine.Localization.Tables.TableReference tableReference, UnityEngine.Localization.Locale locale) (at Library/PackageCache/com.unity.localization@1.3.2/Runtime/Settings/Database/LocalizedDatabase.cs:251)
UnityEngine.Localization.LocalizedTable`2[TTable,TEntry].GetTableAsync () (at Library/PackageCache/com.unity.localization@1.3.2/Runtime/Localized Reference/LocalizedTable.cs:147)
UnityEngine.Localization.LocalizedTable`2[TTable,TEntry].GetTable () (at Library/PackageCache/com.unity.localization@1.3.2/Runtime/Localized Reference/LocalizedTable.cs:156)
Yarn.Unity.UnityLocalisedLineProvider.Start () (at Library/PackageCache/dev.yarnspinner.unity@b307dc9547/Runtime/LineProviders/UnityLocalisedLineProvider.cs:52)```

**Comment by desplesda** [comment]
Fixed in 9fd5e0dc3a8c15b90f20d56d8ae75ba4a74da698. Thank you!
