### ISSUE TITLE
Indent/Dedent Issue With Unity Add Line Tags

### ISSUE THREAD

**Issue by virtualosus** [YarnSpinnerTool/YarnSpinner-Unity#215]
**What is the current behavior?**
When I add line tags to my Yarn script from Unity, it is adding <indent to 4> and <dedent from 4> on my jumps and sets within my options

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Write Yarn script - create options - modify variable on option select - add line tags in Unity - <indent to 4> and <dedent from 4> added to option in Yarn script

![55](https://user-images.githubusercontent.com/72548933/203842963-b912fc66-9ac4-4df5-9e36-08a2af2b2d3d.png)

add line tags in Unity....

![56](https://user-images.githubusercontent.com/72548933/203843036-52a6b6a2-f992-45e8-93b3-5d2218a79f08.png)
 

**What is the expected behavior?**
Not have the extra characters applied to Yarn script, only line tags

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2.3
  - Unity Version: 2021.3.13f1

**Other information** 

![57](https://user-images.githubusercontent.com/72548933/203843825-3140f4de-a070-47c8-ad81-4e7bd93a7e53.png)

![58](https://user-images.githubusercontent.com/72548933/203843837-5cd617a7-733d-4e2a-bf7e-0486b2c3282a.png)

**Comment by nefyodovve** [comment]
+1

I have encountered the same problem and it is very frustrating to manually remove all these indent/dedent lines.

Also it corrupts lines with set/declare keyword:
`<<declare $Apologize = false as bool>>` -> `<<declare $Apologize=falseasbool>>`
`<<set $MasterSearch to false>>` -> `<<set $MasterSearchtofalse>>`

**Comment by lowercasename** [comment]
This is affecting me too. Hoping a fix can be put in soon!

**Comment by McJones** [comment]
hmm this was meant to close when https://github.com/YarnSpinnerTool/YarnSpinner/issues/343 was closed
