### ISSUE TITLE
Unexpected locale-aware string conversions cause problems when calling commands with float variables as arguments in some locales

### ISSUE THREAD

**Issue by fmoo** [YarnSpinnerTool/YarnSpinner-Unity#218]
**What is the current behavior?**

When using custom commands that expect float parameters in yarn, e.g., `<<sleep>>`  float literals (e.g., `<<sleep 0.5>>`) behave as expected.  However, when using variables (such as `<<sleep {$delay}>>` in a locale that uses "." as a thousands separator, such as de-AT, the float is converted to a locale aware string (e.g., "0,5") but then back to a float using an InvariantCulture when calling the custom command.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Run the following in an OnAwake() somewhere to force the system locale to German (AT).
```
using System.Globalization;
// ...
        void Awake() {
            Thread.CurrentThread.CurrentCulture = new CultureInfo("de-AT");
            Thread.CurrentThread.CurrentUICulture = new CultureInfo("de-AT");
        }
```

Then in a yarn script:
```
<<declare $delay = 0.5>>
Let's wait for a half-second...
<<wait {$delay}>>
Done!
```

The "Done" dialogue will take 5 seconds to appear instead of 0.5 seconds.

**What is the expected behavior?**

Since we are using a properly typed float variable, and passing it to a command that expects a float, I expect there to be no unnecessary computations of string formatting or parsing to happen, and the "Done" dialogue to appear after a half-second delay instead of five seconds.

Locale aware string formatting would still be expected when using `{$value}` to format a float var into user-visible dialogue, as well as commands that expect strings/text but a float was passed.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2.1+ (0d3916269ce9542c5e52774af530db581758dabe)
  - Unity Version: 2019.4.36f1

**Other information** 
[Link to discord discussion in #help](https://discord.com/channels/754171172693868585/754171643990900776/1058888714278948904)

**Comment by McJones** [comment]
This was partially fixed as referenced in https://github.com/YarnSpinnerTool/YarnSpinner/issues/369 but the long term issue persists.
For now the `format_invariant` method provides a workaround until we can come to some long term solution.
