### ISSUE TITLE
Stack Traces missing from Unhandled Exceptions in Custom Handlers

### ISSUE THREAD

**Issue by fmoo** [YarnSpinnerTool/YarnSpinner-Unity#223]
**Is your feature request related to a problem? Please describe.**

When I write bad c# code in a custom command or function, and it throws at runtime (e.g., attempting to call a method on a null reference), Unity reports the exception stack only against `Dialogue.Continue()`, with no context about my error.

**Describe the solution you'd like**
I'd like to see the stack for my custom handler when the error is reported via Unity, to make it clear it's a problem with my code and not some internal problem inside of Yarn core.

Separately, it would be nice to include context about which .yarn file/line triggered the error, but this seems like a much more challenging problem.

**Describe alternatives you've considered**
It's unclear what other options are really available.  I usually end up adding <<Log>> commands within my relevant scripts to narrow things down to a command or function, and from there I can easily use the debugger or additional logging inside my handler.

**Additional context**
Am running yarnspinner 2.2.x, Unity 2019.3.4.36f1

**Comment by McJones** [comment]
This has since been fixed.
Exceptions thrown by commands are now passed back up allowing for seeing what line threw the issue.
