### ISSUE TITLE
"Add Line Tags To Scripts" can duplicate line IDs

### ISSUE THREAD

**Issue by Fscibe** [YarnSpinnerTool/YarnSpinner-Unity#225]
**What is the current behavior?**
We noticed some line ID duplication can occur when using "Add Line Tags To Scripts".

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
- Add these 3 fake .yarn files to a yarn project -> [YarnLoadTest.zip](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/files/10862317/YarnLoadTest.zip)
- Click on "Add Line Tags To Scripts"
-> notice some duplicated IDs

![image](https://user-images.githubusercontent.com/825388/222173903-0e9bc2cb-0520-4cb6-aa24-a01cbf1f0ccb.png)

**What is the expected behavior?**
- No ID duplication

**Please tell us about your environment:**
  - Yarn Spinner Version: 2.2.4
  - Unity Version: 2021.3.15f1

**Other information** 
In 'YarnProjectUtility.AddLineTagsToFilesInYarnProject' method, the 'allExistingTags' list is not updated after each call to Yarn.Compiler.Utility.AddTagsToLines.
Parsing the file to get the new line IDs and adding them to the allExistingTags solved the issue on our side.

**Comment by cjacobwade** [comment]
I'm seeing this too!

**Comment by Invertex** [comment]
Hey, would you mind forking and adding your edit to your fork? This is an issue in our project as well and it would be nice to not have to dig into this. I tried a quick fix by redoing the call that assigns to allExistingTags each time that foreach loop after it runs, but that does not appear to be enough.

Cheers!
