### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by mlbustin** [YarnSpinnerTool/YarnSpinner-Unity#229]
**When importing a package with github, I get two errors**

**I import the package through the package manager as it usually does, then I get two errors**:

**1. Library\PackageCache\dev.yarnspinner.unity@720b6c94da\Runtime\LineProviders\UnityLocalisedLineProvider.cs(330,105): error CS0117: 'UnityLocalisedLineProvider' does not contain a definition for 'stringsTable'
2. Library\PackageCache\dev.yarnspinner.unity@720b6c94da\Runtime\LineProviders\UnityLocalisedLineProvider.cs(331,103): error CS0117: 'UnityLocalisedLineProvider' does not contain a definition for 'assetTable'**

**Please tell us about your environment:**
  
  - Yarn Spinner Version: latest
  - Unity Version: 2022.2.12f1, 2022.1.13f1, 2021.3.22f1

**Comment by McJones** [comment]
This was fixed with the 2.3.1 release. I am closing this issue for now but if the error reappears please open another.
