### ISSUE TITLE
DialogueUI - support class extending

### ISSUE THREAD

**Issue by ScrapGames** [YarnSpinnerTool/YarnSpinner-Unity#23]
Just a very simple request to be officially changed 👍 
DialogueUI line 275, is it possible to set method DoRunLine as **protected virtual** instead of private so that we can extend this and tweak as needed.  Thankyou!

**Comment by desplesda** [comment]
The architecture for DialogueUI is changing significantly in 2.0, so depending on what you need this changed for, this might already be in a situation that meets your needs!

**Comment by ScrapGames** [comment]
> The architecture for DialogueUI is changing significantly in 2.0, so depending on what you need this changed for, this might already be in a situation that meets your needs!

Awesome! I look forward to it then! :D
Mainly for text handling, dealing with markup and custom textmesh pro images etc.

I'll close the request and keep an eye out when 2.0 is out
