### ISSUE TITLE
AudioLineProvider tries to run last line of dialogue before having it load

### ISSUE THREAD

**Issue by amesterSim** [YarnSpinnerTool/YarnSpinner-Unity#230]
**What is the current behavior?**
The AudioLineProvider is loading dialogue from a script. Due to some boolean checks the first dialogue to be spoken is the last line of dialogue that is loaded. In checking stack trace, the DialogueRunner attempts to read the last line of dialogue before it has fully loaded (presumably due to a race condition).

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Create a YarnProject with a single script. This Project needs to have multiple lines, with a boolean that makes you skip to the last line. This will make it so Yarn is trying to speak the last line that is being loaded.

**What is the expected behavior?**
I expect the AssetLoadComplete function to remove a pendingLoadOperation from the dictionary AFTER it has been added to the completedLoadOperations

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2.4
  - Unity Version: 2021.3.13f1

**Other information** 
**Original Code Snippet**
![BrokenCode](https://user-images.githubusercontent.com/93539432/230657742-72de2d7d-a7ba-424d-ae13-1ded654c83cf.PNG)

        
**Fixed Version**
![FixedCode](https://user-images.githubusercontent.com/93539432/230657726-39c8f09f-5e7c-44e4-b665-f3eaa4c64b76.PNG)

**Comment by amesterSim** [comment]
**EDIT/UPDATE:**

With further testing on this issue we have noticed that the bug is present when moving to another node outside of the starting node. When moving to another node it seems that the DialogueRunner handles the concurrent process of starting the dialogue and loading the resources differently than when starting a dialogue from the start.

This can be better tested and observed if using any script with multiple nodes. This requires use of the AudioLineProvider and VoiceOverView.

**Comment by McJones** [comment]
Fixed in 8089131e682f15d9dd1b073cc55ca817d0125e28
