### ISSUE TITLE
2023.2.0a14 requires package changes.

### ISSUE THREAD

**Issue by vertxxyz** [YarnSpinnerTool/YarnSpinner-Unity#233]
As of [2023.2.0a14 (see patch notes)](https://unity.com/releases/editor/alpha/2023.2.0a14#:~:text=mode%20dropdown%20button.-,uGUI%3A%20Merged%20TextMesh%20Pro%20(com.unity.textmeshpro)%20into%20uGUI%20(com.unity.ugui)%20and%20deprecate%20the%20TextMesh%20Pro%20package.,-UI%20Toolkit%3A%20Changed) `com.unity.textmeshpro` has been merged into uGUI `com.unity.ugui`.

**What is the current behavior?**
The `com.unity.textmeshpro` package throws errors due to it being deprecated, and no longer supported by this editor version. It cannot be removed as YarnSpinner has a dependency on it.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Add YarnSpinner to a 2023.2.0a14+ project.

**What is the expected behavior?**
No errors.

**Please tell us about your environment:**
  - Yarn Spinner Version: 2.2.4
  - Unity Version: 2023.2.0a14

**Other information** 
YarnSpinner currently has a dependency on `com.unity.textmeshpro`. This will not be allowed as of 2023.2.0a14, and just causes errors.
The fix (which I may make a PR for) is to make TMP an optional dependency, and use version defines to handle the 3 cases:
- No TMP or UGUI version >2.0.0
- TMP
- UGUI version >2.0.0

**Comment by vertxxyz** [comment]
I would make a PR, but the contributing guidelines are advising I work from develop, where no develop branch seems to exist. Should I just be working from the head of main?

**Comment by desplesda** [comment]
Thank you for the heads-up! Yes, make a PR against `main`. I'll update the contribution guidelines.

**Comment by vertxxyz** [comment]
See PR https://github.com/YarnSpinnerTool/YarnSpinner-Unity/pull/234

**Comment by McJones** [comment]
Closed in #234
