### ISSUE TITLE
SetProject() not (actually) working

### ISSUE THREAD

**Issue by Torres-Git** [YarnSpinnerTool/YarnSpinner-Unity#251]
**What is the current behavior?**
While on Build or with "Use Existing Build" addressable setting. After loading and calling `SetProject()` on the current DialogueRunner, the function runs, with no errors, but the Current project gets set to null, even tho the parameter used is not null.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
While on Build or with "Use Existing Build" addressable setting. try to load a yarn project and use it as a parameter in the `SetProject()` method

**What is the expected behavior?**
Actually changing the current yarn project

**Please tell us about your environment:**
  - Yarn Spinner Version:  2.3.1
  - Unity Version: 2022.3.7f1
  - Load Logic:
![Capture](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/assets/59922515/7f6de154-84d0-4c56-87f3-a0519528504b)

**Other information** 
Forcing reference as seen below, results in the same behaviour
![image](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/assets/59922515/fd926342-bef5-4a07-a030-8217aae62791)

**Comment by McJones** [comment]
I can reproduce this on release but not with what's on main. This was fixed as part of #246
