### ISSUE TITLE
Adding voice clips requires Yarn Project Apply button click.

### ISSUE THREAD

**Issue by Bryan-Legend** [YarnSpinnerTool/YarnSpinner-Unity#259]
After I add a new voice over file to the Assets Folder, the audio clips will not be played in game unless I somehow edit the Yarn Project and click the Apply button as shown in the inspector screenshot here. Then the new voice over clips are played correctly.

![image](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/assets/920120/e2e202b7-6dfa-4942-a91d-4060765906fd)

The system should be smart enough to detect a new audio clip is present. Or there needs to be a refresh command or something.

**Comment by Bryan-Legend** [comment]
Also, the docs for the voice over system could use some work. There's not really a page for it on https://docs.yarnspinner.dev/. I had to figure it out by the samples.

**Comment by Bryan-Legend** [comment]
Speaking of the samples, this problem happened on the Intro sample when it was first installed! I had to edit the Intro yarn project and hit apply to get the VOs to work.

**Comment by Bryan-Legend** [comment]
Thank you @McJones

**Comment by McJones** [comment]
ah so good catch I totally only fixed the import ordering, not the post added issue.
