### ISSUE TITLE
AddCommandHandler<string[]> doesn't register command with arbitrary number of parameters

### ISSUE THREAD

**Issue by dario-zubovic** [YarnSpinnerTool/YarnSpinner-Unity#260]
**What is the current behavior?**
If method is registered with `AddCommandHandler<string[]>` instead of `[YarnCommand]`, it's not registered correctly and throws error at play time:
![image](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/assets/7289043/aafaf524-ff63-4d9e-9002-4b2f927a8804)

**What is the expected behavior?**
It's expected that `AddCommandHandler` method behaves the same as `YarnCommand` attribute and register command that takes arbitrary number of parameters.

**Please tell us about your environment:**
  - Yarn Spinner Version: 2.4.0
  - Unity Version: 2022.3.10f1

**Other information** 
```
Can't call command (X): incorrect number of parameters
UnityEngine.Debug:LogError (object)
Yarn.Unity.DialogueRunner:HandleCommand (Yarn.Command) (at ./Library/PackageCache/dev.yarnspinner.unity@2.4.0/Runtime/DialogueRunner.cs:903)
Yarn.VirtualMachine:RunInstruction (Yarn.Instruction)
Yarn.VirtualMachine:Continue ()
Yarn.Dialogue:Continue ()
Yarn.Unity.DialogueRunner:ContinueDialogue (bool) (at ./Library/PackageCache/dev.yarnspinner.unity@2.4.0/Runtime/DialogueRunner.cs:1142)
Yarn.Unity.DialogueRunner:SelectedOption (int) (at ./Library/PackageCache/dev.yarnspinner.unity@2.4.0/Runtime/DialogueRunner.cs:1083)
Yarn.Unity.OptionsListView/<<RunOptions>g__OptionViewWasSelectedInternal|15_2>d:MoveNext () (at ./Library/PackageCache/dev.yarnspinner.unity@2.4.0/Runtime/Views/OptionsListView.cs:176)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
```

**Comment by desplesda** [comment]
Fixed in f4dc45be64a5993a26ee0bbea931e24646f1bb6c, and backported to v2 in 237d5de777b5085cf1ba9b25ee1f44d5a3e590cf . Thank you!
