### ISSUE TITLE
DialogueUI: Changes made in the MarkLineComplete function aren't available to the rest of the class

### ISSUE THREAD

**Issue by Crembotz** [YarnSpinnerTool/YarnSpinner-Unity#27]
I have a continue button with an OnClick event which calls the MarkLineComplete function from the DialogueUI class. Immediately after the function ends, the userRequestedNextLine bool that is set to true in it immediately reverts back to false even though it is not set anywhere in the class to false and the MarkLineComplete function was indeed called. Further more, I've added an extra random bool that is not used anywhere in the code and the same happens to it as well.
Using Yarn version 1.1.0
Using Unity version 2019.4.0f1

**Comment by desplesda** [comment]
This behaviour no longer exists as of version 2.0. As such, I'll close this issue here; thanks for filing the report!
