### ISSUE TITLE
Project Import Error

### ISSUE THREAD

**Issue by dnid-gsexauer** [YarnSpinnerTool/YarnSpinner-Unity#272]
**What is the current behavior?**

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

**What is the expected behavior?**

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 
  - Unity Version:

**Other information**

**Comment by McJones** [comment]
Hello,
There isn't enough information here to help diagnose the issue.
I am going to close this issue, if the error persists please open a new issue with more information so we can help.
Thanks.
