### ISSUE TITLE
How does YarnParameter attribute work?

### ISSUE THREAD

**Issue by heshuimu** [YarnSpinnerTool/YarnSpinner-Unity#282]
For context, I'm trying to attribute YarnCommand onto a method that has an enum type parameter. 

The documentation only has the type reference of YarnParameter, but does not demonstrate how it can be used. The change log does have a mention of YarnParameter, but it's only mentioned to work with `Component` types. 

I then tried to survey the YarnSpinner source code and see where the attributes are being reference, but I could not find any usages. 

So, how are YarnParameter attributes used in the code?

**Comment by desplesda** [comment]
YarnParameter is part of an older approach to how `YarnCommand` and `YarnFunction` methods work, and is no longer in Yarn Spinner as of v3 Beta 1.
