### ISSUE TITLE
Expose YarnProjectImporter.GenerateStringsTable as public method

### ISSUE THREAD

**Issue by nrvllrgrs** [YarnSpinnerTool/YarnSpinner-Unity#292]
I would like to create a line database, allowing users to search for specific lines.

I believe exposing `YarnProjectImporter.GenerateStringsTable` as a public method would allow users to parse the YarnProject data more easily in editor.

While it is possible to export all of the YarnProjects as CSV files and then parse those files into the database, I would prefer cutting out that additional step and pull data directly from the StringTableEntry data structure.

**Comment by desplesda** [comment]
Done. Thank you!
