### ISSUE TITLE
Style tags not getting properly parsed

### ISSUE THREAD

**Issue by fkchaud** [YarnSpinnerTool/YarnSpinner-Unity#32]
**What is the current behavior?**
Trying to use the style tags given by Yarn Editor produces this error, causing the Yarn file not getting compiled and not being able to select it as a valid YarnProgram.
```
Error on line 6 at position 3:
mismatched input ']' expecting FORMAT_FUNCTION_EXPRESSION_START
[b]Azul:[/b] Pintoresque, isn't it?
  ^
```

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
1. Create a simple Yarn file with style tags in the body. I.e.:
```
title: Start
tags: 
colorID: 0
position: 117,-143
---
[b]Azul:[/b] Pintoresque, isn't it?
[b]Alan:[/b] Meh, it's just a house
===
```
2. Try to import that file in Unity.
3. Error raised.

**What is the expected behavior?**
Import should be successful, and dialogue in TextMeshPro should have the appropiate text styles.

**Please tell us about your environment:**
  - Yarn Spinner Version: 1.2.7 - installed via Package Manager using GIT url
  - Unity Version: 2019.4.1f1

**Comment by desplesda** [comment]
Hi! Thanks for filing this issue!

The tags generated by Yarn Editor were implemented before format functions were added to the language. Yarn Editor needs to be updated in order to remove or otherwise deal with this.

Starting in Yarn Spinner 2.0, however, this kind of markup will be natively supported.

**Comment by JoBiden** [comment]
Is there any temporary work around to include styled text?

**Comment by desplesda** [comment]
This behaviour no longer exists as of version 2.0 - the attributes system now correctly parses this syntax. As such, I'll close this issue here; thanks for filing the report!
