### ISSUE TITLE
Report: Lines with inline expressions not getting placeholders

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner-Unity#33]
**What is the current behavior?**

A user in Slack has reported that lines that include inline expressions are being rendered in the generated .CSV files as their original source, rather than having their inline expressions replaced with markers.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

The following line:

```
It’s the first day of opening your very own senior dog sanctuary, {$sanctuaryName}! #line:0777ce1
```

is apparently appearing verbatim, sans the `#line:` tag, in the CSV.

**What is the expected behavior?**

The expression `{$sanctuaryName}` should be replaced with `{0}`.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 
  - Unity Version:

**Other information**

**Comment by Calesi** [comment]
Yarn Spinner Version: 1.1.0

Unity Version: 2019.4.0f1

**Comment by desplesda** [comment]
I haven't been able to reproduce this issue in 2.0 Beta 4. As such, I'll close this issue here; please let me know if you're still encountering this problem!
