### ISSUE TITLE
Creating a new Yarn asset should automatically apply default settings so I don't get the apply / revert popup when deselecting

### ISSUE THREAD

**Issue by cjacobwade** [YarnSpinnerTool/YarnSpinner-Unity#37]
**What is the current behavior?**
Creating a Yarn asset and then deselecting it gives the popup requiring me to choose Apply or Revert even if I haven't made any changes.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
- Use Unity 2019.3
- Create a Yarn asset
- Deselect asset
- See popup

**What is the expected behavior?**
In OnEnable of the importer logic should check if the asset is new and call ApplyAndImport

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.6
  - Unity Version: Unity 2019.3.15f1

**Other information** 

Adding some check on the yarn asset to see if it has been imported yet and if not to force an Apply/Import would resolve this issue. I'm just forcing an ApplyAndImport in OnEnable to avoid this atm

**Comment by desplesda** [comment]
This behaviour no longer exists as of version 2.0. As such, I'll close this issue here; thanks for filing the report!
