### ISSUE TITLE
No nodes have been compiled error when cheking for nodes

### ISSUE THREAD

**Issue by Consalv0** [YarnSpinnerTool/YarnSpinner-Unity#39]
**What is the current behavior?**
I have a function that checks if the node Im running is already in the compiled nodes, using
`dialogueRunner.NodeExists(startNode)` but when there are no nodes, this error log is thrown to the console

`Tried to call NodeExists, but no nodes have been compiled!
UnityEngine.Debug:LogError(Object)
Yarn.Unity.<>c:<CreateDialogueInstance>b__44_9(String) (at Library/PackageCache/dev.yarnspinner.unity@0a071dc884/Runtime/DialogueRunner.cs:560)
Yarn.Dialogue:NodeExists(String)
Yarn.Unity.DialogueRunner:NodeExists(String) (at Library/PackageCache/dev.yarnspinner.unity@0a071dc884/Runtime/DialogueRunner.cs:295)
Game.Dialogue.DialogueInvoker:Start() (at Assets/Game/Dialogue/DialogueInvoker.cs:41)`

**What is the expected behavior?**
I think it should be a warning, since im checking if there are nodes in order to add missing nodes.

**Please tell us about your environment:**
  - Yarn Spinner Version: 1.2.6
  - Unity Version: 2020.1.0f1

**Comment by desplesda** [comment]
Fixed in YarnSpinnerTool/YarnSpinner@505c270!
