### ISSUE TITLE
Can't create shortcut options with only one character

### ISSUE THREAD

**Issue by archer3cl** [YarnSpinnerTool/YarnSpinner-Unity#40]
**What is the current behavior?**
Creating an shortcut option with only one characters makes the Yarn Importer thrown an error, without message.
Adding a second character makes the error go away

This throws an error
-> A

This is OK
-> AB

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Fresh Yarn installation via git url 

**What is the expected behavior?**
Being able to create shortcut options with only one character

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.7
  - Unity Version: 2020.1.2f1

**Comment by desplesda** [comment]
This is now fixed, as of a recent beta!
