### ISSUE TITLE
Updating yarn script with Unity remote config

### ISSUE THREAD

**Issue by jonathaniscarroll** [YarnSpinnerTool/YarnSpinner-Unity#41]
I have a dream of creating new dialogue as my users progress through the game. 
Unity's Remote Config lets me update a string variable, where I can store the text of my yarn script and change it from unity dashboard. 
How do I update/recompile my yarn dialogue with this new string at runtime?

**Comment by radiatoryang** [comment]
See issue #43 ... as I mentioned there, the current design of Yarn Spinner v2.0 is about precompiling in Unity Editor and avoiding runtime compilation. 

If you want to use v1.2.7 instead, then I believe runtime compilation is possible with DialogueRunner.AddScript() and you'd just need code to connect your Unity Remote Config to Yarn Spinner

Good luck!

**Comment by desplesda** [comment]
Closing this issue as a duplicate of #43.
