### ISSUE TITLE
No languages are configured when importing the Yarn Spinner for Unity package (Workaround available)

### ISSUE THREAD

**Issue by desplesda** [YarnSpinnerTool/YarnSpinner-Unity#48]
## Workaround Available

**PLEASE NOTE:** A workaround to this issue is available at the bottom of this issue.

## Bug Report

**What is the current behavior?**

When importing the Yarn Spinner for Unity package, no language configuration is set up. This causes all of the sample content that use a localisation database (which is most of them) to fail to load their lines, because they don't know which language to load.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Import the Yarn Spinner for Unity package into an empty project, and then import the Start Here sample. Run the scene, and an exception will be thrown.

**What is the expected behavior?**

The Yarn Spinner for Unity package should do some setup to prevent this issue.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: v2.0.0-beta1
  - Unity Version: 2019.4.11f1

**Other information** 

This issue can be resolved by configuring the project to have a language:

* Open the Edit menu, and choose Project Settings.
* Click Yarn Spinner.
* Select the language you wish to use (currently, all of the samples only have lines in English, so if you want to use them, select that), and click Add Language to Project.
* Turn on the Has Audio checkbox.

The samples should now run without issue.

**Comment by radiatoryang** [comment]
some proposed solutions here --

1. this is not the best politics, but: the vast majority of Yarn Spinner users are English speaking, and we may want to just automatically initialize a default English language config

2. alternative is to copy the design and implementation of Text Mesh Pro's on-first-import wizard pop-up: 
![image](https://user-images.githubusercontent.com/2285943/104076399-f5e84c80-51e3-11eb-8960-1fd29f48ba24.png)

3. do both, default to English, and warn the user we're defaulting to English in the first time pop-up

4. do nothing, and don't force users to create global language settings... which you only need for localization or voice over, and if you're not using either, it's an extra abstraction that might get in the way of yarn spinner's (relative) simplicity... I've added language overrides in PR #62 which fix the Samples to work out of the box

**Comment by desplesda** [comment]
This behaviour no longer exists as of v1.0-beta3 - Yarn Projects now store their own language, which upon creation defaults to the local machine's current locale. As a result, I'll close this issue.
