### ISSUE TITLE
Variable Declaration not saving the description field on the first apply click.

### ISSUE THREAD

**Issue by Necrospasm** [YarnSpinnerTool/YarnSpinner-Unity#49]
**What is the current behavior?**

Declaring variables doesn't add the description in the .yarnprogram file when you click apply once. It saves it on the second apply click.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Go to the variable declaration script and add a new variable. Put in a description and hit apply. Description is not saved in the file. Clicking apply again, will now save the description too.

**What is the expected behavior?**

Saving all filled in fields with one apply.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: v2.0.0-beta1
  - Unity Version: 2019.4.12f1

**Comment by McJones** [comment]
Closed in #137
