### ISSUE TITLE
OnNodeComplete not called when a node contains options inside a conditional

### ISSUE THREAD

**Issue by HigginDazs** [YarnSpinnerTool/YarnSpinner-Unity#50]
**What is the current behavior?**
A node has a conditional statement. In one branch, it has no options, in the other it has options. If the dialogue finishes without seeing the options, the node is does not call OnNodeComplete. OnNodeComplete is only called if the options are seen.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Using the Space example scene, modify the Sally node in the Sally.yarn file as below:
`<<if visited("Sally") is false>>
    Player: Hey, Sally.
    Sally: Oh! Hi.
    Sally: You snuck up on me.
    Sally: Don't do that.
<<else>>
    Player: Hey. 
    Sally: Hi.
    [[See you later.|Sally.Exit]]
<<endif>>`
When the player first speaks, they won't get the option, as it is not in the conditional branch. Thus, if the player has already visited the "Sally" node, it should play the second branch, and give the player the option. However, this does not happen, as the OnNodeComplete is never called. If a node contains options *anywhere*, is it never considered to complete until the options are selected?

**What is the expected behavior?**
Even if the options are not seen, the node should should call OnNodeComplete if the end of the node is reached.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.7
  - Unity Version: 2020.1.2f1

**Comment by desplesda** [comment]
This behaviour no longer exists as of version 2.0. As such, I'll close this issue here; thanks for filing the report!
