### ISSUE TITLE
Clicking "Update Localizations" creates new files instead of modifying the existing ones

### ISSUE THREAD

**Issue by fkchaud** [YarnSpinnerTool/YarnSpinner-Unity#53]
### What is the current behavior?
Clicking "Update Localizations" creates new files instead of modifying the existing ones.

### Please provide the steps to reproduce, and if possible a minimal demo of the problem:
1. Have a Yarn with added line tags and an existing localization file.
2. Add a new line to the Yarn file, without a line tag.
3. Add the line tag in Unity using the "Add Line Tags" button.
4. Click on Update Localization.

### What is the expected behavior?
**Expected:** Existing localization files are modifying to add the new lines.
**Result:** New localization files are created, forcing me to copy the content from the new ones to the old ones, or reassign them to the Yarn import settings.

### Please tell us about your environment
  - Yarn Spinner Version: 1.2.7
  - Unity Version: 2019.4.9f1

### Other information
**Workaround:** Copy the content from the new CSV files to the old ones, and delete the new ones; or delete the old ones and add the new reference to the yarn import settings.

Important to note that the new localization files are not _entirely_ new as they keep the translation from the existing localizations. So it knows there's a file, it just for some reason decides to duplicate them instead of modifying the current one.

**Comment by desplesda** [comment]
This behaviour has been replaced as of Beta 4, and localisation files are now only ever created when the user manually ask to create one. As such, I'll close this issue here. Thanks for filing the report!
