### ISSUE TITLE
The previous instance of Yarn.Unity.YarnProgramImporterEditor was not un-loaded properly.

### ISSUE THREAD

**Issue by Katsutoshii** [YarnSpinnerTool/YarnSpinner-Unity#54]
## Current Behavior: 
After updating import settings in Yarn Program in the Unity Editor, starting the scene produces the following error:
`The previous instance of Yarn.Unity.YarnProgramImporterEditor was not un-loaded properly. The script has to be declared in a file with the same name.`

## Steps to reproduce
Add a new Yarn Script to a Yarn Program, and apply import settings.
![inspector](https://user-images.githubusercontent.com/22205099/97902170-0cf55480-1cf2-11eb-889e-2e1ef5636880.png)
Hit play, see error logged in console:
![console](https://user-images.githubusercontent.com/22205099/97902291-3ada9900-1cf2-11eb-86c2-a9b665890e4d.png)

## Environment

  - Yarn Spinner Version: 2.0-preview
  - Unity Version: 2020.1.10f

**Comment by desplesda** [comment]
Fixed in 8abfbb1! Thanks, @radiatoryang!
