### ISSUE TITLE
Use addressables flag should set ADDRESSABLES define

### ISSUE THREAD

**Issue by unknowndevice** [YarnSpinnerTool/YarnSpinner-Unity#55]
**Is your feature request related to a problem? Please describe.**

Right now the _use addressables_ flag in project settings is only visible once ADDRESSABLES has been set in the defines. A lot of people don't know about defines. They'll only know they need to add this define if they look at the yarn spinner source code. And defines are set per platform, so if someone changes platform this define will have to be set again.

**Describe the solution you'd like**

Instead what should happen is the _use addressables_ flag should always be visible (unless you can't install the package like in 2018, then have it greyed out). once you tick to _use addressables_ an editor function should automatically add the ADDRESSABLES define. (this can also auto add it when switching between platforms)

**Comment by desplesda** [comment]
This behaviour no longer appears as of `2.0-beta4`; the Editor UI is now a bit smarter about how to present the option to use addressables. As such, I'll close this issue here. Thanks for filing it!
