### ISSUE TITLE
DialogueRunner startAutomatically crashes

### ISSUE THREAD

**Issue by awardell** [YarnSpinnerTool/YarnSpinner-Unity#58]
**What is the current behavior?**
If you are using the DialogueRunner.cs component and turn on ```startAutomatically```, it will throw an error and fail to run. See callstack:

```
InvalidOperationException: visited is not a valid function
Yarn.Library.GetFunction (System.String name) (at <ea7944590845437f86a978879988482b>:0)
Yarn.VirtualMachine.RunInstruction (Yarn.Instruction i) (at <ea7944590845437f86a978879988482b>:0)
Yarn.VirtualMachine.Continue () (at <ea7944590845437f86a978879988482b>:0)
Yarn.Dialogue.Continue () (at <ea7944590845437f86a978879988482b>:0)
Yarn.Unity.DialogueRunner.ContinueDialogue () (at Assets/Vendor/YarnSpinner/Runtime/DialogueRunner.cs:918)
Yarn.Unity.DialogueRunner.<StartDialogue>g__RunDialogue|22_0 (Yarn.Unity.DialogueRunner+<>c__DisplayClass22_0& ) (at Assets/Vendor/YarnSpinner/Runtime/DialogueRunner.cs:259)
Yarn.Unity.DialogueRunner.StartDialogue (System.String startNode) (at Assets/Vendor/YarnSpinner/Runtime/DialogueRunner.cs:248)
Yarn.Unity.DialogueRunner.StartDialogue () (at Assets/Vendor/YarnSpinner/Runtime/DialogueRunner.cs:235)
Yarn.Unity.DialogueRunner.Start () (at Assets/Vendor/YarnSpinner/Runtime/DialogueRunner.cs:545)
```

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Set up the DialogueRunner in the Inspector as shown:
![DialogueRunner Inspector Setup](https://i.imgur.com/GFeLaVH.png)
(Note that I am using a custom DialogueUIBehaviour but that is unrelated to this issue. DialogueUI.cs will suffice)
Run the program and you will note that the error appears in the console and the story does not properly execute.

If you modify DialogueRunner.cs at line 544 from:
```
if (startAutomatically) {
    StartDialogue();
}
```
to
```
            if (startAutomatically) {
                StartCoroutine(WaitThenStartDialogue());
            }
        }

        private IEnumerator WaitThenStartDialogue()
	{
            yield return null;
            StartDialogue();
        }
```
then it will behave as expected.

**What is the expected behavior?**
startAutomatically should start the Story automatically without errors.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.6
  - Unity Version: 2020.1.15f1

It seems that during the first frame, perhaps something is not properly loaded yet. However, I am unsure if my solution is a good solution or just a bandaid over a deeper issue. And still perhaps waiting a frame is the correct solution, but there should at least be a more human understandable error to let the user know not to run dialogue immediately.

**Comment by radiatoryang** [comment]
hello, this is addressed in PR #75 and now awaiting review for merging into v2.0.0 ... thanks for the bug report!
