### ISSUE TITLE
Old shortcuts stay visible after jumping to a new node that only contains shortcuts

### ISSUE THREAD

**Issue by sashaikaia** [YarnSpinnerTool/YarnSpinner-Unity#63]
**What is the current behavior?**

Using the Visual Novel Example, If you have a series of nodes with shortcut options but no actual dialogue, the shortcut from a previous node will remain on screen until a new one renders on top of it. So, if you jump to a node with fewer shortcuts, the old one remains visible. The Dialogue Runner gets stuck if you choose any of the "leftover" shortcuts. 

If you put a line of dialogue before the shortcuts, so something populates into DialogText, or check "Run Selected Option As Line" in the Dialogue Runner, it fixes this behavior. But when there's nothing to display in DialogText, the old shortcuts don't get cleared out upon jumping to the next node. 

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

In the Visual Novel Example Scene, replace "VNExampleDialogue" yarn file with the code at bottom of this report. Run the Visual Novel Scene. 

Click on "menu," you'll jump to the node "Meals." Then, click on "desserts," to jump to the node "Desserts."

The "desserts" shortcut remains on the screen. If you click on "desserts" again, you'll be stuck. If you click on "Start" to return to the Start node, you'll notice that shortcuts for "Dessert2," "Start," and "desserts" all remain on the screen. Clicking on any of these throws the following error: 

> ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: 1 is not a valid option ID (expected a number between 0 and 0.
> Yarn.VirtualMachine.SetSelectedOption (System.Int32 selectedOptionID) (at <568ba28e787942e2ac684546ece69d26>:0)
> Yarn.Dialogue.SetSelectedOption (System.Int32 selectedOptionID) (at <568ba28e787942e2ac684546ece69d26>:0)
> Yarn.Unity.DialogueRunner.<CreateDialogueInstance>g__SelectedOption|69_6 (System.Int32 obj) (at Library/PackageCache/dev.yarnspinner.unity@65ffd6c4be/Runtime/DialogueRunner.cs:784)
> Yarn.Unity.DialogueUI.SelectOption (System.Int32 optionID) (at Library/PackageCache/dev.yarnspinner.unity@65ffd6c4be/Runtime/Views/DialogueUI.cs:474)
> Yarn.Unity.DialogueUI+<>c__DisplayClass22_0.<DoRunOptions>b__0 () (at Library/PackageCache/dev.yarnspinner.unity@65ffd6c4be/Runtime/Views/DialogueUI.cs:398)
> UnityEngine.Events.InvokableCall.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent.cs:166)
> UnityEngine.Events.UnityEvent.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent/UnityEvent_0.cs:58)
> UnityEngine.UI.Button.Press () (at /Applications/Unity/Hub/Editor/2019.4.16f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
> UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at /Applications/Unity/Hub/Editor/2019.4.16f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
> UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at /Applications/Unity/Hub/Editor/2019.4.16f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
> UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at /Applications/Unity/Hub/Editor/2019.4.16f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:261)
> UnityEngine.EventSystems.EventSystem:Update() (at /Applications/Unity/Hub/Editor/2019.4.16f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)
> 

**What is the expected behavior?**

All the shortcuts from the previous node should clear before the new shortcuts appear. The behavior is corrected by simply adding some dialog to each node, before the shortcuts, or selecting "Run Selected Line as Option," though these will require an extra click after the dialog to load the new shortcuts. 

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0.0 Beta 2 
  - Unity Version: 2019.4.16f1

**Other information**
It's possible this is just a really uncommon use-case, that you'd want to load new shortcuts without displaying any dialog? 

Here are the contents of the yarn file used to reproduce the bug: 

```
title: Start
tags:
---
//uncomment the DialogText in each node, or check "Run Selected Option As Line" to correct the behavior. 
->menu
    <<jump Meals>>

===
title: Meals
tags:
---
//meals
->breakfast
    <<jump Breakfast>>
->lunch
    <<jump Lunch>>
->dinner
    <<jump Dinner>>
->desserts
    <<jump Desserts>>
===
title: Desserts
tags:
---
//desserts
->Dessert1
    <<jump Dessert1>>
->Dessert2
    <<jump Dessert2>>
->Start
    <<jump Start>>
===
```

**Comment by desplesda** [comment]
Fixed in 2cb4f55. Thanks for reporting and fixing, @sashaikaia and @radiatoryang!
