### ISSUE TITLE
Variable name field doesn't persist value when clicking into type dropdown

### ISSUE THREAD

**Issue by xsduan** [YarnSpinnerTool/YarnSpinner-Unity#69]
Oops it's me again!

When you click off of the variable text field into another element without blurring the field it reverts its value back to the original. You have to first click away and then to the type dropdown.

It only seems to be this field, everything else is fine as far as I can tell.

![image](https://user-images.githubusercontent.com/9505910/104861491-b1506580-58f5-11eb-9273-92ac5789b28e.png)

![image](https://user-images.githubusercontent.com/9505910/104861497-b8777380-58f5-11eb-9044-561e11212a91.png)

![image](https://user-images.githubusercontent.com/9505910/104861530-d1802480-58f5-11eb-961b-2a0afae7a57c.png)

YarnSpinner: 2.0.0-beta2
Unity: 2020.2.1f1

**Comment by radiatoryang** [comment]
I looked into this and I can replicate the behavior on Unity 2020.1 too.. but I think this is more like a Unity Editor bug. 

YS currently uses `EditorGUI.DelayedTextField()` in `YarnProgramImporter.DeclarationPropertyDrawer.DrawPropertyField()` which doesn't trigger serialization until the user changes focus (usually by clicking on another GUI control). However, when you click on the type dropdown, it doesn't seem to actually register as a different GUI control, and so the DelayedTextField doesn't save the change and the enum control reverts it.

I imagine we could do some workaround, where we put a fake invisible button that hovers over the enum dropdown, but that's probably unwise. Unity should probably just fix their enum dropdown code instead.

In the meantime, the workaround for this is simple -- don't click on the dropdown after you type something. Instead, click basically anywhere else.

**Comment by xsduan** [comment]
good enough for me, hopefully unity will get their stuff together soon
