### ISSUE TITLE
GetComponent<DialogueRunner>().Stop() doesn't stop execution

### ISSUE THREAD

**Issue by eporral1** [YarnSpinnerTool/YarnSpinner-Unity#7]
Is that the right way to stop the execution of the dialogue?

**Comment by afk-mario** [comment]
I managed to do it with this 

`dialogueUI.DialogueComplete ();`

**Comment by desplesda** [comment]
This issue has been open for a while, and I haven't seen many other users reporting similar errors. I'll close this here; please let me know if you're still seeing issues like this. Thanks for filing the bug report!

**Comment by nefyodovve** [comment]
@desplesda I'm here with the same problem. @afk-mario's advice did not help, but @satanas's workaround did the job (thank you very much!). I used the following code to stop the dialogue from the game:

```cs
if (dialogueRunner.IsDialogueRunning)
    dialogueView.DismissLine(() =>
    {
        dialogueRunner.Stop();
        dialogueRunner.StartDialogue("Stop");
    });
```
where "Stop" is empty node.

**Comment by ngauthier12** [comment]
I wish to bump this issue. I am still experiencing this issue as of today. dialogueRunner.Stop() does not close the views currently open, and there are no calls to get the same behaviour as <<stop>> as comment in C# code states :
`Stop is defined inside the Virtual Machine (the compiler traps it and makes it a special case.)`
I have tried calling DismissLine on every active view, without success.
This is required to handle interruptions external to yarn may that need to shut down the runner from outside the dialogue.

**Comment by sayezz** [comment]
I'll bump this because I can't find a way to cancel/interrupt a running dialogue by a user interaction.
