### ISSUE TITLE
Localization asset should handle .CSV files, not .yarn file importer?

### ISSUE THREAD

**Issue by radiatoryang** [YarnSpinnerTool/YarnSpinner-Unity#77]
**Is your feature request related to a problem? Please describe.**
So there's a big problem with the localization workflow now -- each .yarn file is in charge of importing its own localization .csv files, and then forwarding that string table to the Localization Asset.

That means if you have 5 .yarn files, then you'll have 5 .csv files * X languages to track. If you have many different .yarn files, that means many different .csv files. This isn't really workable and heavily discourages using more than 1 .yarn file.

**Describe the solution you'd like**
Localizers generally would much prefer to work with one spreadsheet instead of many little spreadsheets. Which I think means the .csv import, tracking, and refresh should be handled by each language's Localization asset instead of the individual .yarn files. The Localization asset is already where you refresh AudioClip voice over, so I think it makes sense for this to also be the place where you refresh the entire string table from a .csv file.

**Describe alternatives you've considered**
You could just use 1 .yarn file, and that way you get to keep all your localization in one convenient CSV. But that runs counter to typical YS user practice and Yarn Spinner's general design pattern.

**Additional context**
I can try to work on this and submit a PR, but it'll probably take a while and might involve a moderately intrusive refactor.

**Comment by desplesda** [comment]
This preferred solution is now implemented as of Beta 4. Thanks for filing the issue!
