### ISSUE TITLE
Yarn Spinner Input Being Weird?!

### ISSUE THREAD

**Issue by SethDharma** [YarnSpinnerTool/YarnSpinner-Unity#81]
There seems to be a bug I just cant fix. To start dialogue I have triggers, and if the player is in that trigger and presses (E) then it calls the start dialogue. BUT, for some reason there's 2 other keys that trigger it as well, (Lft Ctrl & Lft Mouse Button). Are there default inputs for Yarn Spinner, I literally can't figure this one out.

**Comment by desplesda** [comment]
This issue hasn't seen much more discussion, so I'll close it here. If you're still seeing issues like this, please reopen this issue!
