### ISSUE TITLE
ignoreCase option for MarkupParseResult.TryGetAttributeWithName

### ISSUE THREAD

**Issue by unknowndevice** [YarnSpinnerTool/YarnSpinner-Unity#84]
**Is your feature request related to a problem? Please describe.**

`TryGetAttributeWithName` relies on the attribute in a yarn file always being set to same case as the way the function retrieves. `[shake amount=2]` vs `[shake Amount=2]` will cause an error. I think this kind of difference will not be obvious to a non programmer trying to use attributes.

**Describe the solution you'd like**

Please add the option to pass an `ignoreCase` flag to `TryGetAttributeWithName`. Similar what `Enum.TryParse` does.

**Describe alternatives you've considered**

The alternative is using `TryGetAttributeWithName` multiple times with the various possible variants of the attribute you're looking for.

**Comment by McJones** [comment]
There is two parts to this, the first is that `TryGetAttributeWithName` returns the attribute, so essentially the `[shake amount=2]` in its entirety (albeit parsed), the property `shake` itself is extracted from the `Properties` dictionary on the attribute.

On this we feel its important that the property names be case sensitive if only to help remove potential ambiguities when using the short form properties like `[shake=1]` would this allow both `shake` and `Shake` to work? What if you have `[shake=1 Shake=2]`?
If the case insensitivity is a real issue you can get all the keys of the properties dictionary and compare them however you want.
