### ISSUE TITLE
DialogueRunner.Clear() not working as expected

### ISSUE THREAD

**Issue by urumizawa** [YarnSpinnerTool/YarnSpinner-Unity#86]
**What is the current behavior?**
after using clear, if i try to add the same yarn program again it returns the following error: "ArgumentException: An item with the same key has already been added." all done through code by the way.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
DialogueRunner.Add(dialogueProgram)
DialogueRunner.Clear()
DialogueRunner.Add(dialogueProgram)

**What is the expected behavior?**
ArgumentException: An item with the same key has already been added.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 1.2.6
  - Unity Version: 2021.1

**Other information** 
- Clear function clear everything
- a way to check if it has already been added though I am not sure if that would fix the issue since I still won't be able to have 2 nodes with the same name as far as i can tell.
- similar to Add(program), a Delete(program) wouldn't hurt.

**Comment by McJones** [comment]
This was fixed as part of PR #30, closing.
Thanks for filing the issue.
