### ISSUE TITLE
Run options automatically after RunLine is finished

### ISSUE THREAD

**Issue by StolenCheese** [YarnSpinnerTool/YarnSpinner-Unity#88]
**Is your feature request related to a problem? Please describe.**

I cannot find a way to cleanly allow the dialogue runner to skip waiting for `MarkLineComplete` to be called when showing a line that will be responded to by options, short of my current method of caching every line, option and command in the dialogue UI one behind the dialogue runner to do this manually.
**Describe the solution you'd like**

Option to make dialogue runner to skip waiting for user input if the next line to be displayed will be options
**Describe alternatives you've considered**

A method to peek the type of the next line to be displayed so this can be done manually.
**Additional context**

My system has the current line and options buttons displayed side by side (think like the dialogue in zelda botw)

**Comment by McJones** [comment]
For myriad reasons to do this perfectly is literally impossible I think there is a somewhat decent compromise.
We can in many situations easily tell if the next line after a line is an option, so with the following example:
```
a: hi there
b: oh hi
-> so what's up?
-> can I help?
```

We can easily work out that `b: oh hi` is the last line before options and programmatically tag that line as being the last line before options.
That tag could then be extracted as metadata for you to use.
However if we have:
```
a: hi there
b: oh hi

<<if $knowsC>>
a: so c, right?
<<endif>>

-> so what's up?
-> can I help?
```

We can’t know if the last line is `b: oh hi` or `a: so c, right?` until AFTER we have sent one of the lines.
As a solution to fix this I think the best approach is to go something like this:
```
a: hi there
<<if $knowsC>>
b: oh hi
a: so c, right? #lastLine
<<else>>
b: oh hi #lastLine
<<endif>>

-> so what's up?
-> can I help?
```

Essentially let you as the writer to handle the (almost certainly) infrequent edge cases by explicitly flagging a line as the last one, from the perspective of the metadata this would be the same and the line views would be none the wiser.

Thoughts?

**Comment by McJones** [comment]
A solution to this (albeit manually instead of automatically) was provided as part of https://github.com/YarnSpinnerTool/YarnSpinner/pull/319 and #146 you can now build this up yourself.
Thanks for filing the issue.
