### ISSUE TITLE
Any way to get a unity integration with source code

### ISSUE THREAD

**Issue by nekropants** [YarnSpinnerTool/YarnSpinner-Unity#9]
Hey I see the main repo has the source code but the unity repo has the core framework wrapped in a dll. Is there a way to get a unity version with source code?

**Comment by Haapavuo** [comment]
Yes I did this by downloading the YarnSpinner source code from the other repository and added YarnSpinner and YarnSpinner.Compiler folders to my Unity project. I also created asmdefs for those to get dependencies working. And of course you will need to delete the YarnSpinner dlls in order this to work.

**Comment by desplesda** [comment]
For simplicity, we're unlikely to support two different distributions of the same package; if you need access to the underlying Yarn Spinner compiler's source code, you're probably making modifications to it, which means that it won't be useful for us to ship source code as a package. I'd instead suggest doing what @Haapavuo mentioned, and integrating the source code directly into your Assets folder.
