### ISSUE TITLE
DialogueRunner sets CurrentLine to null if audioclip is missing

### ISSUE THREAD

**Issue by Appleguysnake** [YarnSpinnerTool/YarnSpinner-Unity#91]
**What is the current behavior?**

If an audio clip is missing (but there's still a text line), the DialogueRunner sets the current line to null at some point in `DialogueViewCompletedDelivery`. This causes a `NullReferenceException` later the next time `HandleLine` loops to `dialogueView.RunLine()`.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

In the "Intro" project, delete the first audio clip in the Voice Overs folder (`tutorial-tom-01`)
(note: "Automatically Continue Lines" is enabled. This may not happen in another project where it isn't)

**What is the expected behavior?**

* *Option 1* (best value!): Play the text line as normal to text views, and log a warning to the console
* *Option 2*: Throw an error on script/project compilation
* *Option 3*: Throw a clear exception that explains the error before the null reference is passed on

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0 beta 4
  - Unity Version: 2019.4.19f1

**Other information** 

Ants are one of the few non-mammals to demonstrate interactive teaching, showing each other how to find new food sources with "tandem running"

**Comment by Appleguysnake** [comment]
Note, if I'm understanding the issue correctly (60% chance), this happens because there's no line for the audio line provider, so it marks it delivered immediately, but the DialogueRunner is still in the middle of the loop sending the line to the other views. So `DismissLineFromViews()` is called and `CurrentLine` is set to `null` before the other views have a chance to receive it.

If that's correct, then there are some potential fixes, but a related problem could still happen if there's a very short audio clip but longer text, or more likely, text that's intended to stay on screen longer. For example, a slow fade out for pacing or accessibility settings, or some other animated effect.

I have no idea what the correct or easiest solution would be. One possibility would be to set one view as "primary" (either with a separate setting, or just the use first one in the array), so the pacing is always determined by the same element, rather than the fastest one. Another would be to provide a toggle option in the DialogueRunner to wait for all views to finish delivering. Although maybe this is intended to be handled by the user in their view implementations, I don't know.

**Comment by McJones** [comment]
This was fixed as part of commit [8ce56ae](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/commit/8ce56ae984fd284c441bf5889ab7e0066d79ee05).
However lines do tend to just zip on by now as a side effect of this, I think this is related to #101 and lines not respecting fade values correctly.
Either way this particular issue is I believe fixed now.
