### ISSUE TITLE
AudioClips not matched to lines exactly

### ISSUE THREAD

**Issue by Appleguysnake** [YarnSpinnerTool/YarnSpinner-Unity#92]
**What is the current behavior?**

When Yarn looks for the audio clips to match the `#line:` tags, it matches the first one containing the tag, even if it's only part of the name and there's a better match

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

* Create a Yarn Project with a script with one line, tagged `#line:test`
* Point the project to a folder with two audio files, one called `test`, one called `test_something` (not sure how to make sure yarn finds the wrong one first, but this is what I had)
* Yarn will probably attach the wrong clip to the line. If it correctly points the line to `test`, delete that clip and it will assign the other clip to the line

**What is the expected behavior?**

Match only files with exactly matching filenames

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0 beta 4
  - Unity Version: 2019.4.20f1

**Other information** 

Ants not only care for those infected with a disease, they also understand secondary infections and [take special precautions](https://www.pnas.org/content/115/11/2782) when tending to sick ants.

**Comment by desplesda** [comment]
Fixed in 6524e3d.
