### ISSUE TITLE
Yarn Project breaks if script has two identical tags

### ISSUE THREAD

**Issue by Appleguysnake** [YarnSpinnerTool/YarnSpinner-Unity#93]
**What is the current behavior?**

If a script has two lines with identical tags, an error is thrown on compilation, as expected. 
However, after changing the line tags, the project is broken and will say there are no nodes loaded when trying to run dialogue. I can't see any prompt or button to re-scan the scripts (which are still showing the project inspector).

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

In the Intro demo scene, change any line tag to match another line tag (e.g. tutorial-tom-02 to tutorial-tom-01)

**What is the expected behavior?**

Ideally the project should automatically correct itself next time you re-enter Unity after fixing it. 

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0 beta 4
  - Unity Version: 2019.4.20f1

**Other information** 

Some species of ants actually navigate using landmarks in addition to pheremones, so they can find a shorter route home once they've found food.

**Comment by McJones** [comment]
confirmed still existing inside beta5

**Comment by desplesda** [comment]
This is now fixed as of https://github.com/YarnSpinnerTool/YarnSpinner/commit/25c9164bd017b0312ef5b460196af0622bf91a74.
