### ISSUE TITLE
Virtual machine crashes if a new node is started during a wait command

### ISSUE THREAD

**Issue by Appleguysnake** [YarnSpinnerTool/YarnSpinner-Unity#97]
Note: I'm not sure if this is a bug in the Unity or non-Unity part of Yarnspinner, but I'm posting it here because it's happening with the beta, and seems related to #91 so it may be expected behavior by the vm when passed bad input or something like that.  
I don't know how computers work.

**What is the current behavior?**

If a new node is started during a wait command, the wait command continues, interrupts delivery of the new node, and then the Yarn Spinner virtual machine throws a stack empty error at the end of the new node.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

~~I'm honestly not completely sure. It's happening very frequently in my project, but never in the same place twice.~~ 
All I can say for sure is that it's always preceded by the warning I added for the current line being null, so it may be caused by passing the VM a null line or something like that and my error check there is just preventing the Unity part from crashing before this happens. In which case this can be ignored if that other issue is fixed.

**EDIT:**  
I've narrowed down the cause to either the `DoPlayback()` coroutine in `VoiceOverPlaybackUnity.cs`, the `wait` command coroutine in `DialogueRunner.cs`, or the interaction between the two. 

In my project, the situation is triggered by the following:

* First, all nodes are triggered by in-world triggers calling `StartDialogue` on the dialoguerunner, even if something is already playing. I think that's the correct way based on the sample projects but if not, that may be relevant. All of my lines have associated voiceover.
* The first node playing has the following structure:
```
title: FirstNode
---
Here's a long line of dialogue waiting to be shown to the player
<<wait 1>>
Here's another line.
===
```
* If the next node is triggered during the playback of the first or second line, it works normally with no errors.
* If the next node is triggered during the one-second wait, it plays the first line of the second node, but skips to the second line of the second node when the one-second wait coroutine ends. The node then continues to play normally, but the stack empty error is thrown when the second node completes delivery.

**What is the expected behavior?**

The VM shouldn't crash with invalid input (if that's the cause), or should recover from an error like this, or should catch the error and throw a clearer message about what happened.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0 beta 4
  - Unity Version: 2019.4.19f1

**Other information**

A quick and dirty fix is to add `StopAllCoroutines();` at the beginning of `StartDialogue()` in `DialogueRunner`, but I'm sure this will cause some other errors down the line, either with other coroutines, or with user-written yarncommands.

Screenshot of console log - the "it happened again" messages are a quick dirty check I threw in `UpdateLineStatus()` to catch the error in #91, but I have no idea why they're always thrown twice immediately before this stack empty error. 
![2021-05-12 13_04_27-Hivemind - speriment 2 - PC, Mac   Linux Standalone - Unity 2019 4 19f1 Personal](https://user-images.githubusercontent.com/13005877/118016712-b9f4fd80-b323-11eb-838f-aeada401b73c.png)

![2021-05-12 13_09_55-Hivemind - Microsoft Visual Studio](https://user-images.githubusercontent.com/13005877/118016737-c11c0b80-b323-11eb-8110-f49433cb4da5.png)

The actual stack trace of the error:
```
InvalidOperationException: Stack empty.
System.Collections.Generic.Stack`1[T].ThrowForEmptyStack () (at <ef151b6abb5d474cb2c1cb8906a8b5a4>:0)
System.Collections.Generic.Stack`1[T].Pop () (at <ef151b6abb5d474cb2c1cb8906a8b5a4>:0)
Yarn.VirtualMachine+State.PopValue () (at <fb322facd0ad4285bdf3abe6771489bf>:0)
Yarn.VirtualMachine.RunInstruction (Yarn.Instruction i) (at <fb322facd0ad4285bdf3abe6771489bf>:0)
Yarn.VirtualMachine.Continue () (at <fb322facd0ad4285bdf3abe6771489bf>:0)
Yarn.Dialogue.Continue () (at <fb322facd0ad4285bdf3abe6771489bf>:0)
Yarn.Unity.DialogueRunner.ContinueDialogue () (at Library/PackageCache/dev.yarnspinner.unity@a3a35e8140/Runtime/DialogueRunner.cs:1297)
Yarn.Unity.DialogueRunner.DialogueViewCompletedDismissal (Yarn.Unity.DialogueViewBase dialogueView) (at Library/PackageCache/dev.yarnspinner.unity@a3a35e8140/Runtime/DialogueRunner.cs:1401)
Yarn.Unity.DialogueRunner+<>c__DisplayClass86_0.<DismissLineFromViews>b__0 () (at Library/PackageCache/dev.yarnspinner.unity@a3a35e8140/Runtime/DialogueRunner.cs:1386)
Yarn.Unity.DialogueViewBase.DismissLine (System.Action onDismissalComplete) (at Library/PackageCache/dev.yarnspinner.unity@a3a35e8140/Runtime/Views/DialogueViewBase.cs:92)
Yarn.Unity.DialogueRunner.DismissLineFromViews (System.Collections.Generic.IEnumerable`1[T] dialogueViews) (at Library/PackageCache/dev.yarnspinner.unity@a3a35e8140/Runtime/DialogueRunner.cs:1386)
Yarn.Unity.DialogueRunner.DialogueViewCompletedDelivery (Yarn.Unity.DialogueViewBase dialogueView) (at Library/PackageCache/dev.yarnspinner.unity@a3a35e8140/Runtime/DialogueRunner.cs:1262)
Yarn.Unity.DialogueRunner+<>c__DisplayClass73_0.<HandleLine>b__0 () (at Library/PackageCache/dev.yarnspinner.unity@a3a35e8140/Runtime/DialogueRunner.cs:815)
Yarn.Unity.VoiceOverPlaybackUnity+<DoPlayback>d__7.MoveNext () (at Library/PackageCache/dev.yarnspinner.unity@a3a35e8140/Runtime/Views/VoiceOverPlaybackUnity.cs:140)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <a555715ef291462eb190c2c939543f55>:0)
```

**Comment by fmoo** [comment]
fwiw, we've been seeing this on and off for a while on an older version.  Our stack looks like this:
```
InvalidOperationException: Stack empty.
  at System.Collections.Generic.Stack`1[T].Pop () [0x00008] in <ae22a4e8f83c41d69684ae7f557133d9>:0 
  at Yarn.VirtualMachine+State.PopValue () [0x00000] in <60a9cde088b1430eb5c95ed66926df4f>:0 
  at Yarn.VirtualMachine.RunInstruction (Yarn.Instruction i) [0x00142] in <60a9cde088b1430eb5c95ed66926df4f>:0 
  at Yarn.VirtualMachine.Continue () [0x000ae] in <60a9cde088b1430eb5c95ed66926df4f>:0 
  at Yarn.Dialogue.Continue () [0x0000f] in <60a9cde088b1430eb5c95ed66926df4f>:0 
  at Yarn.Unity.DialogueRunner.ContinueDialogue () [0x0000d] in <3964ba3f7c3b4248be52e8b58158f0ad>:0 
  at Yarn.Unity.DialogueRunner+<>c__DisplayClass42_0+<<CreateDialogueInstance>g__DoHandleWait|11>d.MoveNext () [0x0003f] in <3964ba3f7c3b4248be52e8b58158f0ad>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <251be4efae014ce8ac9c16c930d6c8b5>:0 
 
(Filename: <ae22a4e8f83c41d69684ae7f557133d9> Line: 0)
```
