### ISSUE TITLE
Intro example has borked materials when the sample is imported into an already existing URP project

### ISSUE THREAD

**Issue by McJones** [YarnSpinnerTool/YarnSpinner-Unity#98]
**What is the current behavior?**

The intro scene instead of having a space looking background is bright magenta.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

1. Have an existing Unity URP project.
2. Import Yarnspinner beta
3. Import Yarnspinner samples
4. Open Intro sample
5. Run Intro sample

**What is the expected behavior?**

The space materials will not be magenta.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: v2.0.0-beta4
  - Unity Version: 2019.4.11f1

**Other information** 

No thanks

**Comment by desplesda** [comment]
Options:

- Include code that runs when the sample is installed (an asset postprocessor?) detects the presence of the URP package, and automatically runs the URP material upgrader on the sample's assets
- Document the fact that you'll need to run the upgrader manually

Which one is better?

**Comment by desplesda** [comment]
Discussed off-line: it looks like the best approach will be to:

1. Detect that a non-builtin pipeline is in use, and then
2. Show a warning of some kind and a link to documentation explaining how to migrate the materials to the user's render pipeline.

**Comment by McJones** [comment]
closed in #138
